//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ds_dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ds_dersler()
        {
            this.tbl_ds_dersprog = new HashSet<tbl_ds_dersprog>();
            this.tbl_ds_kullanici = new HashSet<tbl_ds_kullanici>();
        }
    
        public byte ds_ders_id { get; set; }
        public string ds_ders_adi { get; set; }
        public Nullable<byte> ds_ders_adres_fkid { get; set; }
    
        public virtual tbl_ds_adres tbl_ds_adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ds_dersprog> tbl_ds_dersprog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ds_kullanici> tbl_ds_kullanici { get; set; }
    }
}
