//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ds_adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ds_adres()
        {
            this.tbl_ds_dersler = new HashSet<tbl_ds_dersler>();
            this.tbl_ds_dersprog = new HashSet<tbl_ds_dersprog>();
            this.tbl_ds_kullanici = new HashSet<tbl_ds_kullanici>();
        }
    
        public byte adres_id { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string mahalle { get; set; }
        public string cadde { get; set; }
        public string sokak { get; set; }
        public string bina_ad { get; set; }
        public string bina_no { get; set; }
        public string kat { get; set; }
        public string postakodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ds_dersler> tbl_ds_dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ds_dersprog> tbl_ds_dersprog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ds_kullanici> tbl_ds_kullanici { get; set; }
    }
}
