//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ds_menu
    {
        public int ds_menu_id { get; set; }
        public string ds_menu_ad { get; set; }
        public string ds_menu_yetki { get; set; }
        public bool ds_menu_aktif { get; set; }
        public Nullable<int> ds_menu_sırala { get; set; }
        public string ds_menu_nav_url { get; set; }
        public Nullable<int> ds_menu_fkid { get; set; }
    }
}
